version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - PORT=8000
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    working_dir: /app
    command: mlflow ui --backend-store-uri sqlite:///mlflow.db --host 0.0.0.0 --port 5050
    restart: always

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: always
